First we want to create multiple dataframes where each one flags different conditions

In [1]:
import numpy as np
import pandas as pd
import csv
import sklearn as sk
from sklearn.model_selection import train_test_split
from sklearn import tree
%run Functions.ipynb
%run FeaturesFunctions.ipynb
import matplotlib.pyplot as plt
from sklearn.metrics import roc_auc_score

loaded functions

In [2]:
Intervals=pd.read_csv("IntervalInfo.csv")

In [6]:
Results=Intervals["Result"]

In [16]:
labels=pd.DataFrame(columns=["ResultA","Resulta","ResultJ","ResultS","ResultN","ResultL","ResultR","Resulte","Resultj","ResultV","ResultE","ResultF","Resultf","ResultQ"])

In [17]:
A=[]
a=[]
J=[]
S=[]
L=[]
R=[]
e=[]
j=[]
V=[]
E=[]
F=[]
f=[]
Q=[]
N=[]


temp=pd.DataFrame(columns=labels.columns)
for Label in Results:
    if (Label=="A"):
        A.append(1)
    else:
        A.append(0)
    if (Label=="a"):
        a.append(1)
    else:
        a.append(0)
    if (Label=="J"):
        J.append(1)
    else:
        J.append(0)
    if (Label=="S"):
        S.append(1)
    else:
        S.append(0)
    if (Label=="N"):
        N.append(1)
    else:
        N.append(0)
    if (Label=="L"):
        L.append(1)
    else:
        L.append(0)
    if (Label=="R"):
        R.append(1)
    else:
        R.append(0)
    if (Label=="e"):
        e.append(1)
    else:
        e.append(0)
    if (Label=="j"):
        j.append(1)
    else:
        j.append(0)
    if (Label=="V"):
        V.append(1)
    else:
        V.append(0)
    if (Label=="E"):
        E.append(1)
    else:
        E.append(0)
    if (Label=="F"):
        F.append(1)
    else:
        F.append(0)
    if (Label=="f"):
        f.append(1)
    else:
        f.append(0)
    if (Label=="Q"):
        Q.append(1)
    else:
        Q.append(0)
labels["ResultA"]=A
labels["Resulta"]=a
labels["ResultJ"]=J
labels["ResultS"]=S
labels["ResultN"]=N
labels["ResultL"]=L
labels["ResultR"]=R
labels["Resulte"]=e
labels["Resultj"]=j
labels["ResultV"]=V
labels["ResultE"]=V
labels["ResultF"]=F
labels["Resultf"]=f
labels["ResultQ"]=Q
print("DONE")
labels.head()

DONE

,ResultA,Resulta,ResultJ,ResultS,ResultN,ResultL,ResultR,Resulte,Resultj,ResultV,ResultE,ResultF,Resultf,ResultQ
0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
1,0,0,0,0,1,0,0,0,0,0,0,0,0,0
2,0,0,0,0,1,0,0,0,0,0,0,0,0,0
3,0,0,0,0,1,0,0,0,0,0,0,0,0,0
4,0,0,0,0,1,0,0,0,0,0,0,0,0,0